In [4]:
import numpy as np
from numpy.linalg import eig
import math

In [13]:
A1 = np.array([[1,1],[1,1]])

A2 = np.array([[1,2,3],[2,3,1],[3,1,2]])

A3 = np.array([[1,2,3],[0,3,1],[0,0,2]])

A4 = np.array([[1,2,3,4],[0,2,3,4],[0,0,3,4],[0,0,0,4]])

A5 = np.array([[0,0,1],[0,1,0],[1,0,0]])

In [28]:
w,v = eig(A1)

In [29]:
w

array([2., 0.])

In [30]:
w,v = eig(A2)

In [31]:
w

array([ 6.        , -1.73205081,  1.73205081])

In [32]:
w,v = eig(A3)

In [33]:
w

array([1., 3., 2.])

In [34]:
w,v = eig(A4)

In [35]:
w

array([1., 2., 3., 4.])

In [36]:
w,v = eig(A5)

In [37]:
w

array([ 1., -1.,  1.])

In [24]:
H = np.array([[2,-4],[-4,6]])
w,v = eig(H)
w

array([-0.47213595,  8.47213595])